branch-defaults:
  master:
    environment: ryp-webapp
    group_suffix: null
global:
  application_name: ryp-calculator-web
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: eu-west-1
  profile: eb-cli
  repository: null
  sc: git
