const formula = [

    {
        day: 1,
        multiplier: 0.8,
        title: 'Dag 1, 12 reps',
        sets: {
            squats: 3,
            benchpress: 2,
            row: 2,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 2,
        multiplier: 0.85,
        title: 'Dag 2, 12 reps',
        sets: {
            squats: 3,
            benchpress: 2,
            row: 2,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 3,
        multiplier: 0.9,
        title: 'Dag 3, 12 reps',
        sets: {
            squats: 3,
            benchpress: 2,
            row: 2,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 4,
        multiplier: 0.95,
        title: 'Dag 4, 8 reps',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 5,
        multiplier: 0.975,
        title: 'Dag 5, 8 reps',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 6,
        multiplier: 1,
        title: 'Dag 6, 8 reps',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 7,
        multiplier: 1.025,
        title: 'Dag 7, 8 reps',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 8,
        multiplier: 1.05,
        title: 'Dag 8, 8 reps',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 9,
        multiplier: 1.075,
        title: 'Dag 9, 8 reps',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 10,
        multiplier: 1.1,
        title: 'Dag 10, 8 reps',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 11,
        multiplier: 1.125,
        title: 'Dag 11, 8 reps',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 12,
        multiplier: 1.15,
        title: 'Dag 12, 8 reps',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 13,
        multiplier: 1.3,
        title: 'Dag 13, 4+1 reps',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 3,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 14,
        multiplier: 1.318,
        title: 'Dag 14, 4+1 reps',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 3,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 15,
        multiplier: 1.336,
        title: 'Dag 15, 4+1 reps',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 3,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 16,
        multiplier: 1.354,
        title: 'Dag 16, 4+1 reps',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 3,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 17,
        multiplier: 1.372,
        title: 'Dag 17, 4+1 reps',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 3,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 18,
        multiplier: 1.39,
        title: 'Dag 18, 4+1 reps',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 3,
            biceps: 2,
            triceps: 2,
        },
    },
];

export default formula;
